### ISSUE TITLE
VS 2022 Community (17.11.2) Can't Open Template 

### ISSUE THREAD

**Issue by grumpymonk** [CommunityToolkit/Maui.NativeLibraryInterop#47]
It seems that the solution in the "template" directory gets no love from Visual Studio Community at this point. Visual Studio Code can open it, but Visual Studio Community just ends up in a completely blank set of windows if opening from File -> Open -> Project/Solution, or self-closes if opening by clicking on the .sln file.

**Comment by rachelkang** [comment]
Hi, @grumpymonk - Thanks for the issue report! This issue appears to be a problem with Visual Studio, so we ask that you use the VS feedback tool to report the issue. With the Report a Problem tool, you can collect detailed information about the problem, and send it to the appropriate team with just a few button clicks.

Go to the [Visual Studio for Windows feedback tool](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) to report the issue and consider adding a link to the VS Feedback issue to the issue here so that others can follow its activity there.
